### ISSUE TITLE
Create multiple targets (modules) inside C7

### ISSUE THREAD

**Issue by paulofaria** [open-swift/C7#18]
SPM supports multiple targets (modules). Maybe having those inside the C7 package would be a good a idea. We could have the `C7` module which would be an umbrella module which `@_exported import` all modules inside `C7` package. This would give us module namespacing. So we could have `Stream.Error` instead of `C7.StreamError`, for example.

This approach could be in all OpenSwift packages. I just created the issue here for specific examples.

**Comment by tanner0101** [comment]
The problem with this would be we have modules with very common names like `Stream`. This could cause collisions between modules, correct?

As much as I love `Stream.Error` we need to be under the unique `C7` namespace.

**Comment by dreymonde** [comment]
Can `Stream` module in this case be referenced as `C7.Stream`?

**Comment by tanner0101** [comment]
Since we're using `@_exported import` it's the same as doing `import Stream` I believe.

**Comment by Danappelxx** [comment]
Did I miss the discussion about this? Otherwise I don't think we should close this.

**Comment by Danappelxx** [comment]
My opinion on this is that it's necessary for C7 (and Open Swift in general), since otherwise we end up with a cluttered repository with a million unindexed files. Another upside is that we get a clear dependency tree and ensure that, for example, `Time` does not depend on `Stream` (unless it makes sense, in which case there would just be an import and a line in the package.swift).
